### ISSUE TITLE
Allow explicit type selection in hiera values

### ISSUE THREAD

**Issue by oxc** [oxc/puppet-rspamd#11]
Allow specifying an explicit type instead of auto when specifying keys in hiera, e.g.

```yaml
domain:
  example.com:
    path: /var/lib/rspamd/dkim/$domain.$selector.key
    'selector: string': 20200822
```

When this is possible, allow arrays to be printed as config-arrays:
```yaml
    rates:
      some_limit:
        selector: 'user.lower'
        'bucket: array':
          - burst: 100
            rate: "10 / 1min"
          - burst: 10
            rate: "100 / 1min"
```
this should result in:
```
rates {
  some_limit {
    selector = "user.lower";
    bucket = [
    {
      burst = 100;
      rate = "10 / 1min";
    },
    {
      burst = 10;
      rate = "100 / 1min";
    }
    ]
  }
}
```

The exact syntax has still TBD, but I believe `key: type` should have the least potential for clashing with future keys/features, while being a common way to specify types in many langauges.
